In [28]:
import pandas as pd
import re
import unicodedata
from pathlib import Path

In [29]:
###  LISTS

## IMDB Top 250
#   constantly refreshing
## Letterboxd Top 250
#   constantly refreshing
## Elgyem Collection
#   updated monthly (10 films added)
## Empire Masterpiece Essays
#   updated monthly (1 film added)

## 1001 Films You Must Watch Before You Die
#   updated annually
## Movies Everyone Should Watch (according to Reddit)
#   seems to be updated every now and then
## Blank Check Discord
#   updated every 2 years
## Edgar Wright's Top 1000
#   updated every few years
## Empire Reader's Top 100
#   updated every few years

## Sight and Sound Poll
#   updated every 10 years
## Network Favourites
#   won't be updated unless I put in a lot of effort
## Guillermo del Toro's Top Films
#   unknown if this will be updated

In [30]:
# df = pd.read_excel('letterboxd.xlsx')
# df['URL'] = df['URL'].str.replace('https://boxd.it/', '')
# df['Year'] = df['Year'].astype(int)
# print(df.head())

In [31]:
def remove_accents(text):
    normalised = unicodedata.normalize('NFKD', text)
    return ''.join(c for c in normalised if not unicodedata.combining(c))

def clean_title(title):
    title = remove_accents(title)
    title = title.lower()
    title = re.sub(r'[^A-Za-z0-9 ]', '', title)

    if title[:4] == "the ":
        title = title[4:]
    elif title[:2] == "a ":
        title = title[2:]
    elif title[:3] == "an ":
        title = title[3:]
    
    return title

In [32]:
lists_folder = Path("lists")
csv_files = lists_folder.glob("*.csv")

dfs = []

for file in csv_files:
    df = pd.read_csv(file, skiprows=4)
    df['List'] = file.stem.replace('-', ' ')
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)
combined_df['URL'] = combined_df['URL'].str.replace('https://boxd.it/', '')
combined_df['Year'] = combined_df['Year'].astype(int)
combined_df['Sort Name'] = combined_df['Name'].apply(clean_title)

C:\Users\Tom\AppData\Local\Temp\ipykernel_1808\3675412222.py:12: FutureWarning: The default value of regex will change from True to False in a future version.
  combined_df['URL'] = combined_df['URL'].str.replace('https://boxd.it/', '')

In [33]:
combined_df.head()

,Position,Name,Year,URL,Description,List,Sort Name
0,1,All of Us Strangers,2023,Bz3C,NaN,1001 before you die,all of us strangers
1,2,The Zone of Interest,2023,gJsA,NaN,1001 before you die,zone of interest
2,3,The Boy and the Heron,2023,ipeM,NaN,1001 before you die,boy and the heron
3,4,Poor Things,2023,tNWU,NaN,1001 before you die,poor things
4,5,Oppenheimer,2023,wUow,NaN,1001 before you die,oppenheimer

In [34]:
film_counts = (
    combined_df.groupby("URL")
      .agg(
          appearances=("URL", "count"),
          name=("Name", "first"),
          year=("Year", "first"),
          lists=("List", list),
          sort=("Sort Name", "first")
      )
      .reset_index()
)

In [35]:
list_values_dict = {'sight and sound' : 5.5,
                    'blank check discord' : 5.4,
                    '1001 before you die' : 5.3,
                    'edgar wright' : 4.8,
                    'empire masterpieces' : 4.7,
                    'letterboxd most fans' : 4.2,
                    'imdb top 250' : 3.8,
                    'movies everyone should watch' : 3.5,
                    'they shoot pictures dont they' : 3.2,
                    'letterboxd top 500' : 3.1,
                    'the tom canon' : 2.7,
                    'elgyem collection' : 2.6,
                    'empire top 100' : 2.1,
                    'best picture' : 1.8,
                    'guillermo del toro' : 1.6,
                    'network favourites' : 1.1,
                    }

def list_value_calc(source_files):
    return sum(list_values_dict.get(f, 0.1) for f in source_files)

film_counts['list values'] = film_counts['lists'].apply(list_value_calc)

In [36]:
film_counts.head()

,URL,appearances,name,year,lists,sort,list values
0,10I4,1,Sayonara,1957,[best picture],sayonara,1.8
1,10Ow,1,Norma Rae,1979,[best picture],norma rae,1.8
2,10f2,1,Son of the White Mare,1981,[letterboxd top 500],son of the white mare,3.1
3,10hC,4,Make Way for Tomorrow,1937,"[1001 before you die, elgyem collection, the t...",make way for tomorrow,13.8
4,10iU,4,La Notte,1961,"[1001 before you die, edgar wright, letterboxd...",la notte,16.4

In [37]:
film_count_counts = (
    film_counts["appearances"]
    .value_counts()
    .sort_index(ascending=False)
    .rename("number of films")
    .to_frame()
)

film_count_counts["cumulative total"] = film_count_counts["number of films"].cumsum()

print(film_count_counts)

    number of films  cumulative total
15                2                 2
14                4                 6
13               15                21
12               16                37
11               27                64
10               34                98
9                42               140
8                54               194
7                76               270
6                87               357
5               120               477
4               221               698
3               322              1020
2               650              1670
1              1871              3541

In [42]:
list_length = 500

filtered_films = film_counts.sort_values(by=["appearances", "list values"], ascending=False)
filtered_films = filtered_films.head(list_length).sort_values(by='sort', ascending=True).reset_index()

for i, row in filtered_films.iterrows():
    print(f"{i+1}. {row['name']} ({row['year']}) - {row['appearances']}")

1. 12 Angry Men (1957) - 12
2. 12 Years a Slave (2013) - 5
3. 1917 (2019) - 5
4. 2001: A Space Odyssey (1968) - 13
5. The 39 Steps (1935) - 5
6. The 400 Blows (1959) - 9
7. 8½ (1963) - 10
8. Ace in the Hole (1951) - 7
9. The Adventures of Robin Hood (1938) - 7
10. After Hours (1985) - 6
11. Aguirre, the Wrath of God (1972) - 5
12. Airplane! (1980) - 8
13. Akira (1988) - 8
14. Ali: Fear Eats the Soul (1974) - 6
15. Alien (1979) - 13
16. Aliens (1986) - 8
17. All About Eve (1950) - 11
18. All About My Mother (1999) - 7
19. All Quiet on the Western Front (1930) - 6
20. All That Heaven Allows (1955) - 6
21. All That Jazz (1979) - 9
22. All the President's Men (1976) - 8
23. Amadeus (1984) - 11
24. Amarcord (1973) - 4
25. Amélie (2001) - 8
26. American Graffiti (1973) - 5
27. An American in Paris (1951) - 5
28. An American Werewolf in London (1981) - 5
29. Anatomy of a Murder (1959) - 6
30. Andrei Rublev (1966) - 7
31. Angels with Dirty Faces (1938) - 4
32. Annie Hall (1977) - 8
33. The Apartment (1960) - 11
34. Apocalypse Now (1979) - 12
35. Army of Shadows (1969) - 7
36. Arrival (2016) - 8
37. The Ascent (1977) - 6
38. Ashes and Diamonds (1958) - 5
39. Assault on Precinct 13 (1976) - 5
40. Avatar (2009) - 6
41. The Awful Truth (1937) - 5
42. Back to the Future (1985) - 12
43. Badlands (1973) - 5
44. Barbie (2023) - 6
45. Barry Lyndon (1975) - 12
46. The Battle of Algiers (1966) - 10
47. Beau Travail (1999) - 5
48. Before Sunrise (1995) - 8
49. Before Sunset (2004) - 7
50. Being John Malkovich (1999) - 6
51. Being There (1979) - 6
52. Belle de Jour (1967) - 5
53. Ben-Hur (1959) - 7
54. The Best Years of Our Lives (1946) - 8
55. Bicycle Thieves (1948) - 10
56. The Big Lebowski (1998) - 9
57. The Big Sleep (1946) - 5
58. The Birds (1963) - 7
59. Black Narcissus (1947) - 6
60. Black Swan (2010) - 5
61. Blade Runner (1982) - 13
62. The Blair Witch Project (1999) - 5
63. Blood Simple (1984) - 5
64. Blow Out (1981) - 7
65. Blow-Up (1966) - 6
66. Blue Velvet (1986) - 8
67. The Blues Brothers (1980) - 5
68. Body Heat (1981) - 4
69. Bonnie and Clyde (1967) - 7
70. Boogie Nights (1997) - 7
71. Boyhood (2014) - 6
72. Brazil (1985) - 9
73. The Breakfast Club (1985) - 5
74. Breathless (1960) - 7
75. Bride of Frankenstein (1935) - 9
76. The Bridge on the River Kwai (1957) - 8
77. Brief Encounter (1945) - 9
78. A Brighter Summer Day (1991) - 7
79. Bringing Up Baby (1938) - 7
80. Broadcast News (1987) - 7
81. Brokeback Mountain (2005) - 10
82. Butch Cassidy and the Sundance Kid (1969) - 6
83. Cabaret (1972) - 9
84. The Cabinet of Dr. Caligari (1920) - 5
85. Carrie (1976) - 6
86. Casablanca (1942) - 14
87. Cat People (1942) - 5
88. Catch Me If You Can (2002) - 5
89. The Celebration (1998) - 5
90. Children of Men (2006) - 9
91. Children of Paradise (1945) - 8
92. Chinatown (1974) - 11
93. Chungking Express (1994) - 9
94. Cinema Paradiso (1988) - 6
95. Citizen Kane (1941) - 12
96. City Lights (1931) - 10
97. City of God (2002) - 10
98. Cléo from 5 to 7 (1962) - 10
99. Clerks (1994) - 4
100. A Clockwork Orange (1971) - 11
101. Close Encounters of the Third Kind (1977) - 7
102. Clueless (1995) - 5
103. Come and See (1985) - 8
104. The Conformist (1970) - 7
105. The Conversation (1974) - 9
106. The Cook, the Thief, His Wife & Her Lover (1989) - 6
107. Cool Hand Luke (1967) - 5
108. The Cranes Are Flying (1957) - 7
109. Cries and Whispers (1972) - 6
110. Crimes and Misdemeanors (1989) - 5
111. Crouching Tiger, Hidden Dragon (2000) - 6
112. Daisies (1966) - 6
113. The Dark Knight (2008) - 11
114. Das Boot (1981) - 5
115. Day for Night (1973) - 7
116. Days of Heaven (1978) - 7
117. Dazed and Confused (1993) - 6
118. Dead Poets Society (1989) - 6
119. Dead Ringers (1988) - 4
120. The Deer Hunter (1978) - 9
121. Deliverance (1972) - 7
122. The Departed (2006) - 6
123. Detour (1945) - 5
124. The Devils (1971) - 5
125. Diabolique (1955) - 5
126. Die Hard (1988) - 9
127. Django Unchained (2012) - 7
128. Do the Right Thing (1989) - 10
129. Dog Day Afternoon (1975) - 7
130. Don't Look Now (1973) - 9
131. Double Indemnity (1944) - 12
132. Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - 12
133. Drive My Car (2021) - 6
134. Duck Soup (1933) - 6
135. Dune: Part Two (2024) - 7
136. The Earrings of Madame de... (1953) - 6
137. Ed Wood (1994) - 5
138. Edward Scissorhands (1990) - 6
139. The Elephant Man (1980) - 10
140. The Empire Strikes Back (1980) - 10
141. Eraserhead (1977) - 5
142. E.T. the Extra-Terrestrial (1982) - 8
143. Eternal Sunshine of the Spotless Mind (2004) - 10
144. Everything Everywhere All at Once (2022) - 10
145. Evil Dead II (1987) - 7
146. The Exorcist (1973) - 8
147. The Exterminating Angel (1962) - 8
148. Eyes Wide Shut (1999) - 6
149. Eyes Without a Face (1960) - 7
150. The Fabelmans (2022) - 5
151. Fallen Angels (1995) - 5
152. Fanny and Alexander (1982) - 8
153. Fantasia (1940) - 6
154. Fantastic Mr. Fox (2009) - 6
155. Fargo (1996) - 11
156. Ferris Bueller's Day Off (1986) - 7
157. Fight Club (1999) - 9
158. Fitzcarraldo (1982) - 6
159. The Fly (1986) - 6
160. Forbidden Planet (1956) - 5
161. Forrest Gump (1994) - 7
162. Frankenstein (1931) - 7
163. Freaks (1932) - 6
164. The French Connection (1971) - 7
165. Full Metal Jacket (1987) - 7
166. Funny Games (1997) - 5
167. The General (1926) - 10
168. Get Out (2017) - 12
169. Ghostbusters (1984) - 9
170. Gladiator (2000) - 8
171. The Godfather (1972) - 15
172. The Godfather Part II (1974) - 14
173. Godzilla (1954) - 7
174. The Gold Rush (1925) - 7
175. Goldfinger (1964) - 4
176. Gone with the Wind (1939) - 7
177. The Good, the Bad and the Ugly (1966) - 13
178. Good Will Hunting (1997) - 6
179. Goodbye, Dragon Inn (2003) - 5
180. GoodFellas (1990) - 14
181. The Graduate (1967) - 8
182. The Grand Budapest Hotel (2014) - 10
183. Grand Illusion (1937) - 6
184. The Grapes of Wrath (1940) - 7
185. Grave of the Fireflies (1988) - 8
186. Grease (1978) - 6
187. The Great Dictator (1940) - 5
188. The Great Escape (1963) - 7
189. The Green Mile (1999) - 5
190. Groundhog Day (1993) - 7
191. Halloween (1978) - 9
192. The Handmaiden (2016) - 8
193. Happy Together (1997) - 4
194. Harakiri (1962) - 5
195. A Hard Day's Night (1964) - 5
196. Harold and Maude (1971) - 7
197. The Heartbreak Kid (1972) - 5
198. Heat (1995) - 12
199. Her (2013) - 7
200. High and Low (1963) - 9
201. Hiroshima Mon Amour (1959) - 8
202. His Girl Friday (1940) - 9
203. The Holdovers (2023) - 5
204. Hot Fuzz (2007) - 6
205. Howl's Moving Castle (2004) - 5
206. The Hustler (1961) - 5
207. I Know Where I'm Going! (1945) - 5
208. if.... (1968) - 5
209. Ikiru (1952) - 10
210. Imitation of Life (1959) - 5
211. In a Lonely Place (1950) - 8
212. In the Heat of the Night (1967) - 5
213. In the Mood for Love (2000) - 11
214. Inception (2010) - 10
215. Indiana Jones and the Last Crusade (1989) - 5
216. Inglourious Basterds (2009) - 11
217. The Innocents (1961) - 7
218. The Insider (1999) - 6
219. Interstellar (2014) - 8
220. Intolerance: Love's Struggle Throughout the Ages (1916) - 5
221. Invasion of the Body Snatchers (1956) - 5
222. The Iron Giant (1999) - 7
223. It Happened One Night (1934) - 6
224. It's a Wonderful Life (1946) - 13
225. Jaws (1975) - 13
226. Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles (1975) - 7
227. JFK (1991) - 6
228. Journey to Italy (1954) - 5
229. Jules and Jim (1962) - 4
230. Jurassic Park (1993) - 11
231. Kes (1969) - 5
232. Kiki's Delivery Service (1989) - 5
233. The Killer (1989) - 6
234. Kind Hearts and Coronets (1949) - 5
235. King Kong (1933) - 7
236. The King of Comedy (1982) - 7
237. Kiss Me Deadly (1955) - 4
238. Koyaanisqatsi (1982) - 4
239. Kwaidan (1964) - 6
240. L.A. Confidential (1997) - 8
241. La Dolce Vita (1960) - 9
242. La Haine (1995) - 8
243. La Jetée (1962) - 4
244. La La Land (2016) - 7
245. Lady Bird (2017) - 8
246. The Last Picture Show (1971) - 8
247. Last Year at Marienbad (1961) - 8
248. L'Atalante (1934) - 6
249. Late Spring (1949) - 7
250. L'Avventura (1960) - 5
251. Lawrence of Arabia (1962) - 10
252. Le Samouraï (1967) - 7
253. L'Eclisse (1962) - 4
254. Léon: The Professional (1994) - 5
255. The Leopard (1963) - 6
256. Let the Right One In (2008) - 5
257. Letter from an Unknown Woman (1948) - 5
258. The Life and Death of Colonel Blimp (1943) - 9
259. Life Is Beautiful (1997) - 5
260. Life of Brian (1979) - 5
261. The Lion King (1994) - 7
262. Little Women (2019) - 8
263. The Lives of Others (2006) - 7
264. Local Hero (1983) - 4
265. The Long Goodbye (1973) - 7
266. The Lord of the Rings: The Fellowship of the Ring (2001) - 13
267. The Lord of the Rings: The Return of the King (2003) - 9
268. The Lord of the Rings: The Two Towers (2002) - 7
269. Lost in Translation (2003) - 8
270. Love Me Tonight (1932) - 5
271. M (1931) - 11
272. Mad Max: Fury Road (2015) - 13
273. The Magnificent Ambersons (1942) - 7
274. Magnolia (1999) - 10
275. Malcolm X (1992) - 5
276. The Maltese Falcon (1941) - 7
277. A Man Escaped (1956) - 6
278. The Man Who Shot Liberty Valance (1962) - 6
279. Man with a Movie Camera (1929) - 5
280. The Manchurian Candidate (1962) - 6
281. Manhattan (1979) - 4
282. Master and Commander: The Far Side of the World (2003) - 6
283. The Matrix (1999) - 12
284. A Matter of Life and Death (1946) - 9
285. McCabe & Mrs. Miller (1971) - 7
286. Mean Streets (1973) - 4
287. Memento (2000) - 9
288. Memories of Murder (2003) - 9
289. Metropolis (1927) - 9
290. Midnight Cowboy (1969) - 7
291. Midnight Run (1988) - 5
292. Millennium Actress (2001) - 5
293. Miller's Crossing (1990) - 5
294. Mirror (1975) - 6
295. Modern Times (1936) - 10
296. Monty Python and the Holy Grail (1975) - 8
297. Moonlight (2016) - 10
298. Moonstruck (1987) - 5
299. Moulin Rouge! (2001) - 5
300. Mr. Smith Goes to Washington (1939) - 8
301. Mrs. Miniver (1942) - 5
302. Mulholland Drive (2001) - 11
303. My Darling Clementine (1946) - 5
304. My Neighbor Totoro (1988) - 10
305. My Night at Maud's (1969) - 5
306. Napoleon (1927) - 5
307. Nashville (1975) - 10
308. Network (1976) - 10
309. The Night of the Hunter (1955) - 11
310. Night of the Living Dead (1968) - 7
311. The Nightmare Before Christmas (1993) - 5
312. No Country for Old Men (2007) - 11
313. North by Northwest (1959) - 8
314. Nosferatu (1922) - 7
315. Notorious (1946) - 6
316. Ocean's Eleven (2001) - 5
317. Oldboy (2003) - 9
318. On the Waterfront (1954) - 8
319. Once Upon a Time in America (1984) - 6
320. Once Upon a Time... in Hollywood (2019) - 8
321. Once Upon a Time in the West (1968) - 10
322. One Flew Over the Cuckoo's Nest (1975) - 11
323. Only Angels Have Wings (1939) - 5
324. Oppenheimer (2023) - 11
325. Ordet (1955) - 6
326. Orpheus (1950) - 5
327. Out of the Past (1947) - 7
328. Paddington 2 (2017) - 5
329. Paisan (1946) - 4
330. Pan's Labyrinth (2006) - 12
331. Paper Moon (1973) - 5
332. Parasite (2019) - 13
333. Paris, Texas (1984) - 11
334. The Passion of Joan of Arc (1928) - 10
335. Past Lives (2023) - 7
336. Pather Panchali (1955) - 5
337. Paths of Glory (1957) - 8
338. Peeping Tom (1960) - 5
339. Perfect Blue (1997) - 6
340. Performance (1970) - 5
341. Persona (1966) - 9
342. Phantom of the Paradise (1974) - 6
343. Phantom Thread (2017) - 8
344. The Philadelphia Story (1940) - 6
345. The Pianist (2002) - 6
346. The Piano (1993) - 10
347. Picnic at Hanging Rock (1975) - 6
348. Pierrot le Fou (1965) - 5
349. Pinocchio (1940) - 5
350. A Place in the Sun (1951) - 5
351. Planet of the Apes (1968) - 5
352. PlayTime (1967) - 8
353. Point Blank (1967) - 4
354. Point Break (1991) - 5
355. Poor Things (2023) - 5
356. Portrait of a Lady on Fire (2019) - 11
357. Possession (1981) - 5
358. The Prestige (2006) - 5
359. The Princess Bride (1987) - 8
360. Princess Mononoke (1997) - 7
361. Psycho (1960) - 11
362. Pulp Fiction (1994) - 13
363. Raging Bull (1980) - 13
364. Raiders of the Lost Ark (1981) - 13
365. Raising Arizona (1987) - 6
366. Ran (1985) - 11
367. Rashomon (1950) - 10
368. Ratatouille (2007) - 8
369. Rear Window (1954) - 11
370. Rebecca (1940) - 6
371. Red Desert (1964) - 4
372. The Red Shoes (1948) - 10
373. Requiem for a Dream (2000) - 6
374. Reservoir Dogs (1992) - 6
375. Rififi (1955) - 7
376. Rio Bravo (1959) - 8
377. RoboCop (1987) - 6
378. Rocky (1976) - 9
379. The Rocky Horror Picture Show (1975) - 5
380. Roma (2018) - 5
381. Roman Holiday (1953) - 7
382. Rome, Open City (1945) - 5
383. Rope (1948) - 5
384. Rosemary's Baby (1968) - 8
385. The Royal Tenenbaums (2001) - 6
386. The Rules of the Game (1939) - 5
387. Rushmore (1998) - 6
388. Sansho the Bailiff (1954) - 6
389. Satantango (1994) - 4
390. Saving Private Ryan (1998) - 8
391. Scarface (1983) - 9
392. Schindler's List (1993) - 10
393. Scream (1996) - 8
394. Se7en (1995) - 11
395. The Searchers (1956) - 7
396. Secrets & Lies (1996) - 5
397. A Separation (2011) - 5
398. A Serious Man (2009) - 8
399. The Servant (1963) - 5
400. Seven Samurai (1954) - 11
401. The Seventh Seal (1957) - 9
402. Shadow of a Doubt (1943) - 5
403. The Shawshank Redemption (1994) - 11
404. Sherlock Jr. (1924) - 10
405. The Shining (1980) - 13
406. The Shop Around the Corner (1940) - 5
407. The Silence of the Lambs (1991) - 12
408. Singin' in the Rain (1952) - 13
409. The Sixth Sense (1999) - 6
410. The Social Network (2010) - 10
411. Solaris (1972) - 7
412. Some Like It Hot (1959) - 9
413. Sorcerer (1977) - 8
414. The Sound of Music (1965) - 9
415. Spartacus (1960) - 6
416. Spider-Man 2 (2004) - 6
417. Spider-Man: Across the Spider-Verse (2023) - 5
418. Spider-Man: Into the Spider-Verse (2018) - 9
419. The Spirit of the Beehive (1973) - 7
420. Spirited Away (2001) - 12
421. Stagecoach (1939) - 5
422. Stalker (1979) - 10
423. Stand by Me (1986) - 9
424. Star Wars (1977) - 15
425. The Sting (1973) - 6
426. Strangers on a Train (1951) - 7
427. Sullivan's Travels (1941) - 7
428. Sunrise: A Song of Two Humans (1927) - 8
429. Sunset Boulevard (1950) - 11
430. Suspiria (1977) - 8
431. Sweet Smell of Success (1957) - 8
432. Synecdoche, New York (2008) - 6
433. Tampopo (1985) - 6
434. Taste of Cherry (1997) - 7
435. Taxi Driver (1976) - 13
436. Terminator 2: Judgment Day (1991) - 12
437. Terms of Endearment (1983) - 5
438. The Texas Chain Saw Massacre (1974) - 9
439. Thelma & Louise (1991) - 5
440. There Will Be Blood (2007) - 12
441. Thief (1981) - 5
442. The Thin Man (1934) - 5
443. The Thing (1982) - 12
444. The Third Man (1949) - 11
445. This Is Spinal Tap (1984) - 5
446. Three Colours: Blue (1993) - 5
447. Three Colours: Red (1994) - 6
448. Throne of Blood (1957) - 8
449. Titanic (1997) - 8
450. To Be or Not to Be (1942) - 9
451. To Kill a Mockingbird (1962) - 7
452. Tokyo Story (1953) - 9
453. Tootsie (1982) - 5
454. Top Hat (1935) - 6
455. Touch of Evil (1958) - 9
456. A Touch of Zen (1970) - 6
457. Toy Story (1995) - 6
458. Trainspotting (1996) - 11
459. The Treasure of the Sierra Madre (1948) - 9
460. The Tree of Life (2011) - 5
461. Trouble in Paradise (1932) - 6
462. The Truman Show (1998) - 7
463. Twin Peaks: Fire Walk with Me (1992) - 7
464. Two-Lane Blacktop (1971) - 4
465. Ugetsu (1953) - 4
466. The Umbrellas of Cherbourg (1964) - 9
467. Un Chien Andalou (1929) - 4
468. Under the Skin (2013) - 5
469. Unforgiven (1992) - 7
470. The Usual Suspects (1995) - 5
471. Vampyr (1932) - 6
472. Vertigo (1958) - 14
473. Vivre Sa Vie (1962) - 5
474. The Wages of Fear (1953) - 7
475. Wake in Fright (1971) - 4
476. WALL·E (2008) - 6
477. West Side Story (1961) - 6
478. When Harry Met Sally... (1989) - 9
479. Where Is the Friend's House? (1987) - 5
480. Whiplash (2014) - 10
481. Who Framed Roger Rabbit (1988) - 6
482. Who's Afraid of Virginia Woolf? (1966) - 6
483. The Wicker Man (1973) - 5
484. The Wild Bunch (1969) - 6
485. Wild Strawberries (1957) - 9
486. Wings of Desire (1987) - 5
487. Withnail & I (1987) - 7
488. Witness for the Prosecution (1957) - 5
489. The Wizard of Oz (1939) - 10
490. The Wolf of Wall Street (2013) - 5
491. A Woman Under the Influence (1974) - 7
492. Y Tu Mamá También (2001) - 7
493. Yi Yi (2000) - 6
494. Yojimbo (1961) - 6
495. The Young and the Damned (1950) - 8
496. Young Frankenstein (1974) - 6
497. The Young Girls of Rochefort (1967) - 8
498. Your Name. (2016) - 5
499. Z (1969) - 6
500. Zodiac (2007) - 6

In [40]:
selection = film_counts[film_counts["appearances"] == 13].sort_values(by="name", ascending=True)
for _, row in selection.iterrows():
    print(f"{row['name']} ({row['year']})")

2001: A Space Odyssey (1968)
Alien (1979)
Blade Runner (1982)
It's a Wonderful Life (1946)
Jaws (1975)
Mad Max: Fury Road (2015)
Parasite (2019)
Pulp Fiction (1994)
Raging Bull (1980)
Raiders of the Lost Ark (1981)
Singin' in the Rain (1952)
Taxi Driver (1976)
The Good, the Bad and the Ugly (1966)
The Lord of the Rings: The Fellowship of the Ring (2001)
The Shining (1980)

In [37]:
film_counts[film_counts['name'] == "Parasite"].head(1).lists.item()

['1001 before you die',
 'best picture',
 'blank check discord',
 'edgar wright',
 'empire top 100',
 'guillermo del toro',
 'imdb top 250',
 'letterboxd most fans',
 'letterboxd top 500',
 'movies everyone should watch',
 'sight and sound',
 'the tom canon',
 'they shoot pictures dont they']

In [41]:
film_counts[film_counts['name'].str.contains("Wuthering Heights")]

,URL,appearances,name,year,lists,sort,list values
1538,25Mi,2,Wuthering Heights,1939,"[1001 before you die, best picture]",wuthering heights,6